"""
Lumina Studio - Backing Plate 形状修复属性测试 (Property-Based Tests)

使用 Hypothesis 验证 _build_color_voxel_mesh 生成 backing plate mesh 的正确性属性。
每个属性测试至少运行 100 次迭代。
"""

import os
import sys

import numpy as np
import pytest
from hypothesis import given, settings, assume
from hypothesis import strategies as st

# Ensure project root is on sys.path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from core.converter import _build_color_voxel_mesh

BACKING_PLATE_RGBA = np.array([245, 245, 245, 255], dtype=np.uint8)


def _extract_pixel_coords_from_mesh(mesh, height: int) -> set[tuple[int, int]]:
    """Extract the set of (row, col) pixel coordinates covered by voxels in the mesh.
    提取 mesh 中所有体素对应的 (row, col) 像素坐标集合。

    Each voxel box has 8 vertices. The X range [x, x+1] maps to column=floor(x_min).
    The Y range [y, y+1] maps to row = height - 1 - floor(y_min) (world Y is flipped).

    Args:
        mesh: trimesh.Trimesh with voxel boxes (8 verts per box).
            (包含体素盒的 trimesh.Trimesh，每个盒 8 个顶点)
        height (int): Original image height for Y-axis inversion.
            (原始图像高度，用于 Y 轴翻转)

    Returns:
        set[tuple[int, int]]: Set of (row, col) pixel coordinates.
            (像素坐标 (row, col) 的集合)
    """
    verts = mesh.vertices
    n_voxels = len(verts) // 8
    coords: set[tuple[int, int]] = set()
    for i in range(n_voxels):
        box_verts = verts[i * 8:(i + 1) * 8]
        x_min = box_verts[:, 0].min()
        y_min = box_verts[:, 1].min()
        col = int(round(x_min))
        world_row = int(round(y_min))
        row = height - 1 - world_row
        coords.add((row, col))
    return coords


# ---------------------------------------------------------------------------
# Hypothesis strategy: generate random mask_solid boolean arrays
# ---------------------------------------------------------------------------
@st.composite
def mask_solid_strategy(draw: st.DrawFn):
    """Generate a random boolean mask_solid array with at least one True pixel.
    生成至少包含一个 True 像素的随机布尔 mask_solid 数组。

    Returns:
        tuple: (mask_solid, height, width)
    """
    h = draw(st.integers(min_value=1, max_value=20))
    w = draw(st.integers(min_value=1, max_value=20))
    # Generate a flat boolean list, then reshape
    flat = draw(st.lists(st.booleans(), min_size=h * w, max_size=h * w))
    mask_solid = np.array(flat, dtype=bool).reshape(h, w)
    # Filter out all-False arrays (function returns None for those)
    assume(np.any(mask_solid))
    return mask_solid, h, w


# ============================================================================
# Property 1: Backing plate 只覆盖实色像素
# Feature: backing-plate-shape-fix, Property 1: Backing plate 只覆盖实色像素
# **Validates: Requirements 1.1**
# ============================================================================

@settings(max_examples=100)
@given(data=mask_solid_strategy())
def test_backing_plate_covers_only_solid_pixels(data):
    """Property 1: Backing plate 只覆盖实色像素

    For any mask_solid boolean array, the backing plate mesh generated by
    _build_color_voxel_mesh should contain voxels at exactly the positions
    where mask_solid is True. No extra voxels, no missing voxels.

    **Validates: Requirements 1.1**
    """
    mask_solid, height, width = data

    mesh = _build_color_voxel_mesh(
        mask=mask_solid,
        height=height,
        width=width,
        total_layers=1,
        shrink=0.0,
        rgba=BACKING_PLATE_RGBA,
    )

    # mesh should not be None since we filtered out all-False masks
    assert mesh is not None, "mesh should not be None for mask with True pixels"

    # Extract pixel coordinates from mesh voxels
    mesh_coords = _extract_pixel_coords_from_mesh(mesh, height)

    # Extract expected coordinates from mask_solid
    rows, cols = np.where(mask_solid)
    expected_coords = set(zip(rows.tolist(), cols.tolist()))

    # Verify exact match: every True pixel has a voxel, every voxel has a True pixel
    assert mesh_coords == expected_coords, (
        f"Pixel coordinate mismatch.\n"
        f"  In mesh but not in mask_solid: {mesh_coords - expected_coords}\n"
        f"  In mask_solid but not in mesh: {expected_coords - mesh_coords}\n"
        f"  mask_solid shape: {mask_solid.shape}, "
        f"  n_true={np.count_nonzero(mask_solid)}, n_voxels={len(mesh_coords)}"
    )

    # Also verify voxel count matches
    n_expected = int(np.count_nonzero(mask_solid))
    n_voxels = len(mesh.vertices) // 8
    assert n_voxels == n_expected, (
        f"Voxel count mismatch: expected {n_expected}, got {n_voxels}"
    )


# ============================================================================
# Property 3: Backing plate Z 跨度为单层
# Feature: backing-plate-shape-fix, Property 3: Backing plate Z 跨度为单层
# **Validates: Requirements 1.4**
# ============================================================================

@settings(max_examples=100)
@given(data=mask_solid_strategy())
def test_backing_plate_z_span_is_single_layer(data):
    """Property 3: Backing plate Z 跨度为单层

    For any non-empty mask_solid, the generated backing plate mesh
    (before scale_transform) should have Z coordinates ranging from 0 to 1,
    representing exactly one voxel layer.

    **Validates: Requirements 1.4**
    """
    mask_solid, height, width = data

    mesh = _build_color_voxel_mesh(
        mask=mask_solid,
        height=height,
        width=width,
        total_layers=1,
        shrink=0.0,
        rgba=BACKING_PLATE_RGBA,
    )

    assert mesh is not None, "mesh should not be None for mask with True pixels"

    z_coords = mesh.vertices[:, 2]
    z_min = z_coords.min()
    z_max = z_coords.max()

    assert z_min == pytest.approx(0.0, abs=1e-9), (
        f"Z min should be 0, got {z_min}"
    )
    assert z_max == pytest.approx(1.0, abs=1e-9), (
        f"Z max should be 1, got {z_max}"
    )


# ============================================================================
# Property 4: Backing plate 顶点颜色为白色
# Feature: backing-plate-shape-fix, Property 4: Backing plate 顶点颜色为白色
# **Validates: Requirements 1.6**
# ============================================================================

@settings(max_examples=100)
@given(data=mask_solid_strategy())
def test_backing_plate_face_colors_are_white(data):
    """Property 4: Backing plate 顶点颜色为白色

    For any non-empty mask_solid, all face colors in the generated backing
    plate mesh should be RGBA(245, 245, 245, 255).

    **Validates: Requirements 1.6**
    """
    mask_solid, height, width = data

    mesh = _build_color_voxel_mesh(
        mask=mask_solid,
        height=height,
        width=width,
        total_layers=1,
        shrink=0.0,
        rgba=BACKING_PLATE_RGBA,
    )

    assert mesh is not None, "mesh should not be None for mask with True pixels"

    face_colors = mesh.visual.face_colors
    expected_color = np.array([245, 245, 245, 255], dtype=np.uint8)

    # Every face should have the exact same white color
    assert face_colors.shape[1] == 4, (
        f"Face colors should have 4 channels (RGBA), got {face_colors.shape[1]}"
    )
    mismatches = ~np.all(face_colors == expected_color, axis=1)
    n_bad = int(np.count_nonzero(mismatches))
    assert n_bad == 0, (
        f"{n_bad}/{len(face_colors)} faces have wrong color. "
        f"First bad color: {face_colors[mismatches][0] if n_bad > 0 else 'N/A'}, "
        f"expected: {expected_color}"
    )
